# Generated by Django 2.1.4 on 2019-01-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='Required_Email',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Is there a specific email address you would like your members to have? (format like @example.tld'),
        ),
    ]
