# Generated by Django 2.1.4 on 2019-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityadmin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
