# Generated by Django 2.1.4 on 2019-01-27 08:01

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0002_auto_20190127_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Location',
            field=places.fields.PlacesField(max_length=255, unique=True),
        ),
    ]
